security:
    providers:
        in_db:
            entity:
                class: App\Entity\User
                property: email

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 10

    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            logout: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: app_user_index

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/card, roles: ROLE_USER }
        - { path: ^/usercard, roles: ROLE_USER }
